spring:
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:system/oracle@10.243.136.57:1521:Eversbox
    username:
    password:
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none